In [1]:
import requests

url = "https://fantasy.premierleague.com/api/bootstrap-static/"

response = requests.get(url)

data = response.json()

data.keys()

dict_keys(['chips', 'events', 'game_settings', 'game_config', 'phases', 'teams', 'total_players', 'element_stats', 'element_types', 'elements'])

In [2]:
len(data["elements"]), len(data["teams"]), len(data["events"]), len(data["element_types"])

(609, 20, 38, 4)

In [3]:
data["elements"][0]

{'can_transact': True,
 'can_select': True,
 'chance_of_playing_next_round': None,
 'chance_of_playing_this_round': None,
 'code': 154561,
 'cost_change_event': 0,
 'cost_change_event_fall': 0,
 'cost_change_start': 0,
 'cost_change_start_fall': 0,
 'price_change_percent': '4.0',
 'price_change_hourly_rate': 137,
 'price_change_projections': [{'offset': 0,
   'projected_percent': '5.0',
   'likelihood': 1},
  {'offset': 1, 'projected_percent': '7.0', 'likelihood': 1},
  {'offset': 2, 'projected_percent': '9.0', 'likelihood': 1}],
 'price_change_locked_until': None,
 'price_change_calibrating': False,
 'dreamteam_count': 0,
 'element_type': 1,
 'ep_next': '4.0',
 'ep_this': '4.0',
 'event_points': 6,
 'first_name': 'David',
 'form': '6.0',
 'id': 1,
 'in_dreamteam': False,
 'news': '',
 'news_added': None,
 'now_cost': 60,
 'photo': '154561.jpg',
 'points_per_game': '6.0',
 'removed': False,
 'second_name': 'Raya Martín',
 'selected_by_percent': '37.9',
 'special': False,
 'squad_number': None,
 'status': 'a',
 'team': 1,
 'team_code': 3,
 'total_points': 6,
 'transfers_in': 29640,
 'transfers_in_event': 29640,
 'transfers_out': 21792,
 'transfers_out_event': 21792,
 'value_form': '1.0',
 'value_season': '1.0',
 'web_name': 'Raya',
 'known_name': '',
 'region': 200,
 'team_join_date': '2024-07-04',
 'birth_date': '1995-09-15',
 'has_temporary_code': False,
 'opta_code': 'p154561',
 'minutes': 90,
 'goals_scored': 0,
 'assists': 0,
 'clean_sheets': 1,
 'goals_conceded': 0,
 'own_goals': 0,
 'penalties_saved': 0,
 'penalties_missed': 0,
 'yellow_cards': 0,
 'red_cards': 0,
 'saves': 1,
 'bonus': 0,
 'bps': 24,
 'influence': '0.0',
 'creativity': '0.0',
 'threat': '0.0',
 'ict_index': '0.0',
 'clearances_blocks_interceptions': 1,
 'recoveries': 8,
 'tackles': 0,
 'defensive_contribution': 0,
 'starts': 1,
 'expected_goals': '0.00',
 'expected_assists': '0.00',
 'expected_goal_involvements': '0.00',
 'expected_goals_conceded': '0.20',
 'corners_and_indirect_freekicks_order': None,
 'corners_and_indirect_freekicks_text': '',
 'direct_freekicks_order': None,
 'direct_freekicks_text': '',
 'penalties_order': None,
 'penalties_text': '',
 'scout_risks': [],
 'scout_news_link': '',
 'influence_rank': 503,
 'influence_rank_type': 67,
 'creativity_rank': 503,
 'creativity_rank_type': 67,
 'threat_rank': 503,
 'threat_rank_type': 67,
 'ict_index_rank': 503,
 'ict_index_rank_type': 67,
 'expected_goals_per_90': 0.0,
 'saves_per_90': 1.0,
 'expected_assists_per_90': 0.0,
 'expected_goal_involvements_per_90': 0.0,
 'expected_goals_conceded_per_90': 0.2,
 'goals_conceded_per_90': 0.0,
 'now_cost_rank': 60,
 'now_cost_rank_type': 1,
 'form_rank': 55,
 'form_rank_type': 6,
 'points_per_game_rank': 55,
 'points_per_game_rank_type': 6,
 'selected_rank': 6,
 'selected_rank_type': 1,
 'starts_per_90': 1.0,
 'clean_sheets_per_90': 1.0,
 'defensive_contribution_per_90': 0.0}

In [4]:
data["teams"][0]

{'code': 3,
 'draw': 0,
 'form': None,
 'id': 1,
 'loss': 0,
 'name': 'Arsenal',
 'played': 0,
 'points': 0,
 'position': 0,
 'short_name': 'ARS',
 'strength': None,
 'team_division': None,
 'unavailable': False,
 'win': 0,
 'link_url': '',
 'strength_overall_home': 4,
 'strength_overall_away': 5,
 'strength_attack_home': 0,
 'strength_attack_away': 0,
 'strength_defence_home': 0,
 'strength_defence_away': 0,
 'pulse_id': 1}

In [5]:
data["events"][0]

{'id': 1,
 'name': 'Gameweek 1',
 'deadline_time': '2026-08-21T17:30:00Z',
 'release_time': None,
 'average_entry_score': 36,
 'finished': False,
 'data_checked': False,
 'highest_scoring_entry': 331434,
 'deadline_time_epoch': 1787333400,
 'deadline_time_game_offset': 0,
 'highest_score': 114,
 'is_previous': False,
 'is_current': True,
 'is_next': False,
 'cup_leagues_created': False,
 'h2h_ko_matches_created': False,
 'can_enter': False,
 'can_manage': False,
 'released': True,
 'ranked_count': 8904519,
 'overrides': {'rules': {},
  'scoring': {},
  'element_types': [],
  'pick_multiplier': None},
 'chip_plays': [{'chip_name': 'bboost', 'num_played': 814606},
  {'chip_name': '3xc', 'num_played': 250816}],
 'most_selected': 411,
 'most_transferred_in': 1,
 'top_element': 115,
 'top_element_info': {'id': 115, 'points': 17},
 'transfers_made': 0,
 'most_captained': 411,
 'most_vice_captained': 1}

In [6]:
data["element_types"]

[{'id': 1,
  'plural_name': 'Goalkeepers',
  'plural_name_short': 'GKP',
  'singular_name': 'Goalkeeper',
  'singular_name_short': 'GKP',
  'squad_select': 2,
  'squad_min_select': None,
  'squad_max_select': None,
  'squad_min_play': 1,
  'squad_max_play': 1,
  'ui_shirt_specific': True,
  'sub_positions_locked': [12],
  'element_count': 67},
 {'id': 2,
  'plural_name': 'Defenders',
  'plural_name_short': 'DEF',
  'singular_name': 'Defender',
  'singular_name_short': 'DEF',
  'squad_select': 5,
  'squad_min_select': None,
  'squad_max_select': None,
  'squad_min_play': 3,
  'squad_max_play': 5,
  'ui_shirt_specific': False,
  'sub_positions_locked': [],
  'element_count': 201},
 {'id': 3,
  'plural_name': 'Midfielders',
  'plural_name_short': 'MID',
  'singular_name': 'Midfielder',
  'singular_name_short': 'MID',
  'squad_select': 5,
  'squad_min_select': None,
  'squad_max_select': None,
  'squad_min_play': 2,
  'squad_max_play': 5,
  'ui_shirt_specific': False,
  'sub_positions_locked': [],
  'element_count': 268},
 {'id': 4,
  'plural_name': 'Forwards',
  'plural_name_short': 'FWD',
  'singular_name': 'Forward',
  'singular_name_short': 'FWD',
  'squad_select': 3,
  'squad_min_select': None,
  'squad_max_select': None,
  'squad_min_play': 1,
  'squad_max_play': 3,
  'ui_shirt_specific': False,
  'sub_positions_locked': [],
  'element_count': 73}]

In [10]:
# 1. player id

identity_fields = [
    "id",
    "first_name",
    "second_name",
    "web_name"
]

for field in identity_fields:
    print(f"{field}: {data['elements'][0][field]}")

id: 1
first_name: David
second_name: Raya Martín
web_name: Raya

In [12]:
# 2.teams and position

team_position_fields = [
    "team",
    "element_type"
]

for field in team_position_fields:
    print(f"{field}: {data['elements'][0][field]}")

team: 1
element_type: 1

In [14]:
# 3. Price & ownership

price = data["elements"][0]["now_cost"] / 10
ownership = data["elements"][0]["selected_by_percent"]

print(f"now_cost: £{price:.1f}m")
print(f"selected_by_percent: {ownership}%")

now_cost: £6.0m
selected_by_percent: 37.9%

In [15]:
# 4. FPL performance


performance_fields = [
    "total_points",
    "form",
    "points_per_game",
    "minutes",
    "goals_scored",
    "assists",
    "clean_sheets"
]

for field in performance_fields:
    print(f"{field}: {data['elements'][0][field]}")

total_points: 6
form: 6.0
points_per_game: 6.0
minutes: 90
goals_scored: 0
assists: 0
clean_sheets: 1

In [16]:
# 5. Expected statistics

expected_stats_fields = [
    "expected_goals",
    "expected_assists",
    "expected_goal_involvements"
]

for field in expected_stats_fields:
    print(f"{field}: {data['elements'][0][field]}")

expected_goals: 0.00
expected_assists: 0.00
expected_goal_involvements: 0.00

In [18]:
# 6. ICT metrics


ict_fields = [
    "ict_index",
    "influence",
    "creativity",
    "threat"
]

for field in ict_fields:
    print(f"{field}: {data['elements'][0][field]}")

ict_index: 0.0
influence: 0.0
creativity: 0.0
threat: 0.0

In [19]:
#7. Availability


availability_fields = [
    "status",
    "chance_of_playing_next_round"
]

for field in availability_fields:
    print(f"{field}: {data['elements'][0][field]}")

status: a
chance_of_playing_next_round: None

In [20]:
# 8. Transfers


transfer_fields = [
    "transfers_in_event",
    "transfers_out_event"
]

for field in transfer_fields:
    print(f"{field}: {data['elements'][0][field]}")

transfers_in_event: 29640
transfers_out_event: 21792

In [21]:
#9. Price changes


price_change_fields = [
    "cost_change_start",
    "cost_change_event"
]

for field in price_change_fields:
    print(f"{field}: {data['elements'][0][field]}")

cost_change_start: 0
cost_change_event: 0

# Day 3 — FPL Fixtures API Exploration

## Task 1: Explore the Fixtures Endpoint
Endpoint:
https://fantasy.premierleague.com/api/fixtures/

Goal:
Understand the structure of fix|ture data and identify fields useful for fixture difficulty analysis./

In [26]:
import requests
import pandas as pd

fixtures_url = "https://fantasy.premierleague.com/api/fixtures/"

fixtures = requests.get(fixtures_url).json()

print("Number of fixtures:", len(fixtures))
print("\nFirst fixture:")
print(fixtures[0])

Number of fixtures: 380

First fixture:
{'code': 2645195, 'event': 1, 'finished': True, 'finished_provisional': True, 'id': 1, 'kickoff_time': '2026-08-21T19:00:00Z', 'minutes': 90, 'provisional_start_time': False, 'started': True, 'team_a': 7, 'team_a_score': 0, 'team_h': 1, 'team_h_score': 3, 'stats': [{'identifier': 'goals_scored', 'a': [], 'h': [{'value': 1, 'element': 12}, {'value': 1, 'element': 15}, {'value': 1, 'element': 26}]}, {'identifier': 'assists', 'a': [], 'h': [{'value': 1, 'element': 8}, {'value': 1, 'element': 10}, {'value': 1, 'element': 557}]}, {'identifier': 'own_goals', 'a': [], 'h': []}, {'identifier': 'penalties_saved', 'a': [], 'h': []}, {'identifier': 'penalties_missed', 'a': [], 'h': []}, {'identifier': 'yellow_cards', 'a': [{'value': 1, 'element': 575}], 'h': [{'value': 1, 'element': 4}]}, {'identifier': 'red_cards', 'a': [], 'h': []}, {'identifier': 'saves', 'a': [{'value': 2, 'element': 110}], 'h': [{'value': 1, 'element': 1}]}, {'identifier': 'bonus', 'a': [], 'h': [{'value': 3, 'element': 15}, {'value': 2, 'element': 10}, {'value': 1, 'element': 12}]}, {'identifier': 'bps', 'a': [{'value': 14, 'element': 184}, {'value': 11, 'element': 173}, {'value': 11, 'element': 190}, {'value': 9, 'element': 194}, {'value': 8, 'element': 104}, {'value': 8, 'element': 188}, {'value': 7, 'element': 195}, {'value': 4, 'element': 492}, {'value': 3, 'element': 183}, {'value': 3, 'element': 584}, {'value': 2, 'element': 575}, {'value': 1, 'element': 182}, {'value': -4, 'element': 176}, {'value': -8, 'element': 175}], 'h': [{'value': 41, 'element': 15}, {'value': 37, 'element': 10}, {'value': 36, 'element': 12}, {'value': 34, 'element': 26}, {'value': 31, 'element': 8}, {'value': 30, 'element': 557}, {'value': 27, 'element': 11}, {'value': 24, 'element': 1}, {'value': 21, 'element': 4}, {'value': 15, 'element': 7}, {'value': 10, 'element': 13}, {'value': 8, 'element': 16}, {'value': 5, 'element': 17}, {'value': 4, 'element': 14}, {'value': 3, 'element': 9}, {'value': 3, 'element': 19}]}, {'identifier': 'defensive_contribution', 'a': [{'value': 10, 'element': 173}, {'value': 9, 'element': 104}, {'value': 9, 'element': 182}, {'value': 8, 'element': 190}, {'value': 7, 'element': 175}, {'value': 7, 'element': 184}, {'value': 6, 'element': 176}, {'value': 6, 'element': 194}, {'value': 5, 'element': 183}, {'value': 3, 'element': 195}, {'value': 3, 'element': 575}, {'value': 1, 'element': 188}, {'value': 1, 'element': 492}, {'value': 1, 'element': 584}], 'h': [{'value': 8, 'element': 15}, {'value': 7, 'element': 7}, {'value': 7, 'element': 12}, {'value': 6, 'element': 11}, {'value': 6, 'element': 13}, {'value': 6, 'element': 557}, {'value': 5, 'element': 8}, {'value': 5, 'element': 10}, {'value': 4, 'element': 4}, {'value': 3, 'element': 19}, {'value': 2, 'element': 14}, {'value': 2, 'element': 16}, {'value': 2, 'element': 17}, {'value': 2, 'element': 26}]}], 'team_h_difficulty': 2, 'team_a_difficulty': 5, 'pulse_id': 0}

In [27]:
fixtures_df = pd.DataFrame(fixtures)

print(fixtures_df.columns.tolist())

['code', 'event', 'finished', 'finished_provisional', 'id', 'kickoff_time', 'minutes', 'provisional_start_time', 'started', 'team_a', 'team_a_score', 'team_h', 'team_h_score', 'stats', 'team_h_difficulty', 'team_a_difficulty', 'pulse_id']

In [30]:
fixtures_df[
    [
        'code', 'event', 'finished', 'finished_provisional', 'id', 'kickoff_time', 'minutes', 'provisional_start_time', 'started', 'team_a', 'team_a_score', 'team_h', 'team_h_score', 'stats', 'team_h_difficulty', 'team_a_difficulty', 'pulse_id'
    ]

        
    
].head(10)

,code,event,finished,finished_provisional,id,kickoff_time,minutes,provisional_start_time,started,team_a,team_a_score,team_h,team_h_score,stats,team_h_difficulty,team_a_difficulty,pulse_id
0,2645195,1,True,True,1,2026-08-21T19:00:00Z,90,False,True,7,0.0,1,3.0,"[{'identifier': 'goals_scored', 'a': [], 'h': ...",2,5,0
1,2645198,1,True,True,4,2026-08-22T11:30:00Z,90,False,True,16,0.0,11,2.0,"[{'identifier': 'goals_scored', 'a': [], 'h': ...",4,2,0
2,2645197,1,True,True,3,2026-08-22T14:00:00Z,90,False,True,8,0.0,9,2.0,"[{'identifier': 'goals_scored', 'a': [], 'h': ...",3,3,0
3,2645199,1,True,True,5,2026-08-22T14:00:00Z,90,False,True,20,1.0,12,2.0,"[{'identifier': 'goals_scored', 'a': [{'value'...",2,2,0
4,2645200,1,True,True,6,2026-08-22T14:00:00Z,90,False,True,13,1.0,18,0.0,"[{'identifier': 'goals_scored', 'a': [{'value'...",2,3,0
5,2645196,1,True,True,2,2026-08-22T16:30:00Z,90,False,True,19,0.0,4,3.0,"[{'identifier': 'goals_scored', 'a': [], 'h': ...",3,3,0
6,2645201,1,True,True,7,2026-08-23T13:00:00Z,90,False,True,2,0.0,5,4.0,"[{'identifier': 'goals_scored', 'a': [], 'h': ...",3,3,0
7,2645202,1,True,True,8,2026-08-23T13:00:00Z,90,False,True,3,1.0,15,2.0,"[{'identifier': 'goals_scored', 'a': [{'value'...",3,5,0
8,2645203,1,True,True,9,2026-08-23T15:30:00Z,90,False,True,14,2.0,17,2.0,"[{'identifier': 'goals_scored', 'a': [{'value'...",4,3,0
9,2645204,1,True,True,10,2026-08-24T19:00:00Z,90,False,True,6,3.0,10,2.0,"[{'identifier': 'goals_scored', 'a': [{'value'...",4,3,0

In [31]:
fixtures_df[
    [
        "event",
        "team_h",
        "team_a",
        "team_h_difficulty",
        "team_a_difficulty",
        "finished"
    ]
].head(10)

   event  team_h  team_a  team_h_difficulty  team_a_difficulty  finished
0      1       1       7                  2                  5      True
1      1      11      16                  4                  2      True
2      1       9       8                  3                  3      True
3      1      12      20                  2                  2      True
4      1      18      13                  2                  3      True
5      1       4      19                  3                  3      True
6      1       5       2                  3                  3      True
7      1      15       3                  3                  5      True
8      1      17      14                  4                  3      True
9      1      10       6                  4                  3      True

In [32]:
gameweek_1 = fixtures_df[
    fixtures_df["event"] == 1
]

print("Fixtures in Gameweek 1:", len(gameweek_1))

gameweek_1[
    [
        "event",
        "team_h",
        "team_a",
        "team_h_difficulty",
        "team_a_difficulty"
    ]
]

Fixtures in Gameweek 1: 10

   event  team_h  team_a  team_h_difficulty  team_a_difficulty
0      1       1       7                  2                  5
1      1      11      16                  4                  2
2      1       9       8                  3                  3
3      1      12      20                  2                  2
4      1      18      13                  2                  3
5      1       4      19                  3                  3
6      1       5       2                  3                  3
7      1      15       3                  3                  5
8      1      17      14                  4                  3
9      1      10       6                  4                  3

In [33]:
teams_df = pd.DataFrame(data["teams"])

teams_df[["id", "name", "short_name"]]

    id            name short_name
0    1         Arsenal        ARS
1    2     Aston Villa        AVL
2    3     Bournemouth        BOU
3    4       Brentford        BRE
4    5        Brighton        BHA
5    6         Chelsea        CHE
6    7   Coventry City        COV
7    8  Crystal Palace        CRY
8    9         Everton        EVE
9   10          Fulham        FUL
10  11       Hull City        HUL
11  12    Ipswich Town        IPS
12  13           Leeds        LEE
13  14       Liverpool        LIV
14  15        Man City        MCI
15  16         Man Utd        MUN
16  17       Newcastle        NEW
17  18   Nott'm Forest        NFO
18  19           Spurs        TOT
19  20      Sunderland        SUN

In [34]:
team_mapping = teams_df[["id", "name"]]

fixtures_named = fixtures_df.merge(
    team_mapping,
    left_on="team_h",
    right_on="id",
    how="left"
)

fixtures_named = fixtures_named.rename(
    columns={"name": "home_team"}
)

fixtures_named = fixtures_named.drop(columns=["id_y"])

fixtures_named = fixtures_named.merge(
    team_mapping,
    left_on="team_a",
    right_on="id",
    how="left"
)

fixtures_named = fixtures_named.rename(
    columns={"name": "away_team"}
)

fixtures_named = fixtures_named.drop(columns=["id"])

fixtures_named[
    [
        "event",
        "home_team",
        "away_team",
        "team_h_difficulty",
        "team_a_difficulty",
        "finished"
    ]
].head(10)

,event,home_team,away_team,team_h_difficulty,team_a_difficulty,finished
0,1,Arsenal,Coventry City,2,5,True
1,1,Hull City,Man Utd,4,2,True
2,1,Everton,Crystal Palace,3,3,True
3,1,Ipswich Town,Sunderland,2,2,True
4,1,Nott'm Forest,Leeds,2,3,True
5,1,Brentford,Spurs,3,3,True
6,1,Brighton,Aston Villa,3,3,True
7,1,Man City,Bournemouth,3,5,True
8,1,Newcastle,Liverpool,4,3,True
9,1,Fulham,Chelsea,4,3,True

In [39]:
home_fixtures = fixtures_named[
    [
        "event",
        "home_team",
        "away_team",
        "team_h_difficulty",
        "kickoff_time",
        "finished"
    ]
].copy()

home_fixtures.columns = [
    "event",
    "team",
    "opponent",
    "difficulty",
    "kickoff_time",
    "finished"
]

home_fixtures["is_home"] = True

In [40]:
away_fixtures = fixtures_named[
    [
        "event",
        "away_team",
        "home_team",
        "team_a_difficulty",
        "kickoff_time",
        "finished"
    ]
].copy()

away_fixtures.columns = [
    "event",
    "team",
    "opponent",
    "difficulty",
    "kickoff_time",
    "finished"
]

away_fixtures["is_home"] = False

In [41]:
team_fixtures = pd.concat(
    [home_fixtures, away_fixtures],
    ignore_index=True
)

team_fixtures.head(10)

,event,team,opponent,difficulty,kickoff_time,finished,is_home
0,1,Arsenal,Coventry City,2,2026-08-21T19:00:00Z,True,True
1,1,Hull City,Man Utd,4,2026-08-22T11:30:00Z,True,True
2,1,Everton,Crystal Palace,3,2026-08-22T14:00:00Z,True,True
3,1,Ipswich Town,Sunderland,2,2026-08-22T14:00:00Z,True,True
4,1,Nott'm Forest,Leeds,2,2026-08-22T14:00:00Z,True,True
5,1,Brentford,Spurs,3,2026-08-22T16:30:00Z,True,True
6,1,Brighton,Aston Villa,3,2026-08-23T13:00:00Z,True,True
7,1,Man City,Bournemouth,3,2026-08-23T13:00:00Z,True,True
8,1,Newcastle,Liverpool,4,2026-08-23T15:30:00Z,True,True
9,1,Fulham,Chelsea,4,2026-08-24T19:00:00Z,True,True

In [42]:
away_fixtures = fixtures_named[
    [
        "event",
        "away_team",
        "home_team",
        "team_a_difficulty",
        "kickoff_time",
        "finished"
    ]
].copy()

away_fixtures.columns = [
    "event",
    "team",
    "opponent",
    "difficulty",
    "kickoff_time",
    "finished"
]

away_fixtures["is_home"] = False

away_fixtures.head(10)

,event,team,opponent,difficulty,kickoff_time,finished,is_home
0,1,Coventry City,Arsenal,5,2026-08-21T19:00:00Z,True,False
1,1,Man Utd,Hull City,2,2026-08-22T11:30:00Z,True,False
2,1,Crystal Palace,Everton,3,2026-08-22T14:00:00Z,True,False
3,1,Sunderland,Ipswich Town,2,2026-08-22T14:00:00Z,True,False
4,1,Leeds,Nott'm Forest,3,2026-08-22T14:00:00Z,True,False
5,1,Spurs,Brentford,3,2026-08-22T16:30:00Z,True,False
6,1,Aston Villa,Brighton,3,2026-08-23T13:00:00Z,True,False
7,1,Bournemouth,Man City,5,2026-08-23T13:00:00Z,True,False
8,1,Liverpool,Newcastle,3,2026-08-23T15:30:00Z,True,False
9,1,Chelsea,Fulham,3,2026-08-24T19:00:00Z,True,False

In [43]:
away_fixtures = fixtures_named[
    [
        "event",
        "away_team",
        "home_team",
        "team_a_difficulty",
        "kickoff_time",
        "finished"
    ]
].copy()

away_fixtures.columns = [
    "event",
    "team",
    "opponent",
    "difficulty",
    "kickoff_time",
    "finished"
]

away_fixtures["is_home"] = False

away_fixtures.head()

,event,team,opponent,difficulty,kickoff_time,finished,is_home
0,1,Coventry City,Arsenal,5,2026-08-21T19:00:00Z,True,False
1,1,Man Utd,Hull City,2,2026-08-22T11:30:00Z,True,False
2,1,Crystal Palace,Everton,3,2026-08-22T14:00:00Z,True,False
3,1,Sunderland,Ipswich Town,2,2026-08-22T14:00:00Z,True,False
4,1,Leeds,Nott'm Forest,3,2026-08-22T14:00:00Z,True,False

In [44]:
team_fixtures = pd.concat(
    [home_fixtures, away_fixtures],
    ignore_index=True
)

team_fixtures = team_fixtures.sort_values(
    by=["team", "event"]
)

team_fixtures.head(20)

,event,team,opponent,difficulty,kickoff_time,finished,is_home
0,1,Arsenal,Coventry City,2,2026-08-21T19:00:00Z,True,True
399,2,Arsenal,Aston Villa,4,2026-08-31T19:00:00Z,False,False
29,3,Arsenal,Chelsea,4,2026-09-06T15:30:00Z,False,True
416,4,Arsenal,Sunderland,3,2026-09-12T19:00:00Z,False,False
422,5,Arsenal,Brighton,3,2026-09-19T14:00:00Z,False,False
50,6,Arsenal,Leeds,2,2026-10-10T11:30:00Z,False,True
448,7,Arsenal,Nott'm Forest,3,2026-10-18T15:30:00Z,False,False
72,8,Arsenal,Everton,3,2026-10-24T14:00:00Z,False,True
468,9,Arsenal,Liverpool,4,2026-11-01T16:30:00Z,False,False
90,10,Arsenal,Hull City,2,2026-11-07T15:00:00Z,False,True
488,11,Arsenal,Newcastle,3,2026-11-21T15:00:00Z,False,False
110,12,Arsenal,Man City,4,2026-11-28T15:00:00Z,False,True
502,13,Arsenal,Brentford,3,2026-12-02T20:00:00Z,False,False
519,14,Arsenal,Spurs,3,2026-12-05T15:00:00Z,False,False
140,15,Arsenal,Bournemouth,3,2026-12-12T15:00:00Z,False,True
150,16,Arsenal,Man Utd,4,2026-12-19T15:00:00Z,False,True
542,17,Arsenal,Crystal Palace,3,2026-12-26T15:00:00Z,False,False
554,18,Arsenal,Fulham,3,2026-12-30T20:00:00Z,False,False
180,19,Arsenal,Ipswich Town,2,2027-01-02T15:00:00Z,False,True
190,20,Arsenal,Brentford,3,2027-01-06T20:00:00Z,False,True

In [45]:
arsenal_fixtures = team_fixtures[
    team_fixtures["team"] == "Arsenal"
].head(5)

arsenal_fixtures

,event,team,opponent,difficulty,kickoff_time,finished,is_home
0,1,Arsenal,Coventry City,2,2026-08-21T19:00:00Z,True,True
399,2,Arsenal,Aston Villa,4,2026-08-31T19:00:00Z,False,False
29,3,Arsenal,Chelsea,4,2026-09-06T15:30:00Z,False,True
416,4,Arsenal,Sunderland,3,2026-09-12T19:00:00Z,False,False
422,5,Arsenal,Brighton,3,2026-09-19T14:00:00Z,False,False

In [46]:
arsenal_average_fdr = arsenal_fixtures["difficulty"].mean()

print("Arsenal next 5 fixtures average difficulty:", round(arsenal_average_fdr, 2))

Arsenal next 5 fixtures average difficulty: 3.2

In [47]:
fixture_ratings = (
    team_fixtures
    .groupby("team")
    .head(5)
    .groupby("team")
    .agg(
        average_difficulty=("difficulty", "mean"),
        next_5_fixtures=("opponent", lambda x: ", ".join(x))
    )
    .reset_index()
)

fixture_ratings["average_difficulty"] = (
    fixture_ratings["average_difficulty"].round(2)
)

fixture_ratings = fixture_ratings.sort_values(
    "average_difficulty"
)

fixture_ratings

,team,average_difficulty,next_5_fixtures
13,Liverpool,2.6,"Newcastle, Nott'm Forest, Ipswich Town, Fulham..."
14,Man City,2.8,"Bournemouth, Crystal Palace, Coventry City, Ma..."
15,Man Utd,2.8,"Hull City, Ipswich Town, Everton, Man City, Fu..."
12,Leeds,2.8,"Nott'm Forest, Brentford, Brighton, Newcastle,..."
18,Spurs,2.8,"Brentford, Newcastle, Nott'm Forest, Everton, ..."
1,Aston Villa,3.0,"Brighton, Arsenal, Hull City, Nott'm Forest, S..."
5,Chelsea,3.0,"Fulham, Brighton, Arsenal, Hull City, Brentford"
3,Brentford,3.0,"Spurs, Leeds, Sunderland, Bournemouth, Chelsea"
8,Everton,3.0,"Crystal Palace, Bournemouth, Man Utd, Spurs, I..."
7,Crystal Palace,3.0,"Everton, Man City, Fulham, Ipswich Town, Leeds"
16,Newcastle,3.0,"Liverpool, Spurs, Bournemouth, Leeds, Hull City"
4,Brighton,3.0,"Aston Villa, Chelsea, Leeds, Coventry City, Ar..."
17,Nott'm Forest,3.0,"Leeds, Liverpool, Spurs, Aston Villa, Coventry..."
11,Ipswich Town,3.2,"Sunderland, Man Utd, Liverpool, Crystal Palace..."
0,Arsenal,3.2,"Coventry City, Aston Villa, Chelsea, Sunderlan..."
10,Hull City,3.2,"Man Utd, Coventry City, Aston Villa, Chelsea, ..."
19,Sunderland,3.2,"Ipswich Town, Fulham, Brentford, Arsenal, Man ..."
6,Coventry City,3.4,"Arsenal, Hull City, Man City, Brighton, Nott'm..."
9,Fulham,3.6,"Chelsea, Sunderland, Crystal Palace, Liverpool..."
2,Bournemouth,3.6,"Man City, Everton, Newcastle, Brentford, Liver..."

In [48]:
team_fixtures["fixture"] = (
    team_fixtures["opponent"]
    + " ("
    + team_fixtures["is_home"].map({True: "H", False: "A"})
    + ")"
)

In [50]:
arsenal_next_5 = (
    team_fixtures[
        team_fixtures["team"] == "Arsenal"
    ]
    .head(5)
    [
        [
            "event",
            "fixture",
            "difficulty"
        ]
    ]
)

arsenal_next_5

     event            fixture  difficulty
0        1  Coventry City (H)           2
399      2    Aston Villa (A)           4
29       3        Chelsea (H)           4
416      4     Sunderland (A)           3
422      5       Brighton (A)           3

In [52]:
# Create the fixture text
next_5_detailed["fixture_with_rating"] = (
    next_5_detailed["fixture"]
    + " - "
    + next_5_detailed["difficulty"].astype(str)
)

# Turn gameweeks into columns
fixture_table = next_5_detailed.pivot(
    index="team",
    columns="event",
    values="fixture_with_rating"
)

# Rename the gameweek columns
fixture_table.columns = [
    f"GW{gw}" for gw in fixture_table.columns
]

# Add average difficulty
fixture_table["Avg Difficulty"] = (
    next_5_detailed
    .groupby("team")["difficulty"]
    .mean()
    .round(2)
)

# Sort by easiest average difficulty
fixture_table = fixture_table.sort_values("Avg Difficulty")

fixture_table

,GW1,GW2,GW3,GW4,GW5,Avg Difficulty
team,,,,,,
Liverpool,Newcastle (A) - 3,Nott'm Forest (H) - 3,Ipswich Town (A) - 2,Fulham (H) - 2,Bournemouth (A) - 3,2.6
Man City,Bournemouth (H) - 3,Crystal Palace (A) - 3,Coventry City (H) - 2,Man Utd (A) - 4,Sunderland (H) - 2,2.8
Man Utd,Hull City (A) - 2,Ipswich Town (H) - 2,Everton (A) - 3,Man City (H) - 4,Fulham (A) - 3,2.8
Leeds,Nott'm Forest (A) - 3,Brentford (H) - 3,Brighton (A) - 3,Newcastle (H) - 2,Crystal Palace (H) - 3,2.8
Spurs,Brentford (A) - 3,Newcastle (H) - 2,Nott'm Forest (A) - 3,Everton (H) - 3,Aston Villa (H) - 3,2.8
Aston Villa,Brighton (A) - 3,Arsenal (H) - 4,Hull City (A) - 2,Nott'm Forest (H) - 3,Spurs (A) - 3,3.0
Chelsea,Fulham (A) - 3,Brighton (H) - 2,Arsenal (A) - 5,Hull City (H) - 2,Brentford (A) - 3,3.0
Brentford,Spurs (H) - 3,Leeds (A) - 3,Sunderland (H) - 2,Bournemouth (A) - 3,Chelsea (H) - 4,3.0
Everton,Crystal Palace (H) - 3,Bournemouth (A) - 3,Man Utd (H) - 4,Spurs (A) - 3,Ipswich Town (H) - 2,3.0
Crystal Palace,Everton (A) - 3,Man City (H) - 4,Fulham (A) - 3,Ipswich Town (H) - 2,Leeds (A) - 3,3.0
Newcastle,Liverpool (H) - 4,Spurs (A) - 3,Bournemouth (H) - 3,Leeds (A) - 3,Hull City (H) - 2,3.0
Brighton,Aston Villa (H) - 3,Chelsea (A) - 4,Leeds (H) - 2,Coventry City (A) - 2,Arsenal (H) - 4,3.0
Nott'm Forest,Leeds (H) - 2,Liverpool (A) - 4,Spurs (H) - 3,Aston Villa (A) - 4,Coventry City (H) - 2,3.0
Ipswich Town,Sunderland (H) - 2,Man Utd (A) - 4,Liverpool (H) - 4,Crystal Palace (A) - 3,Everton (A) - 3,3.2
Arsenal,Coventry City (H) - 2,Aston Villa (A) - 4,Chelsea (H) - 4,Sunderland (A) - 3,Brighton (A) - 3,3.2
Hull City,Man Utd (H) - 4,Coventry City (A) - 2,Aston Villa (H) - 3,Chelsea (A) - 4,Newcastle (A) - 3,3.2
Sunderland,Ipswich Town (A) - 2,Fulham (H) - 2,Brentford (A) - 3,Arsenal (H) - 4,Man City (A) - 5,3.2
Coventry City,Arsenal (A) - 5,Hull City (H) - 2,Man City (A) - 5,Brighton (H) - 2,Nott'm Forest (A) - 3,3.4
Fulham,Chelsea (H) - 4,Sunderland (A) - 3,Crystal Palace (H) - 3,Liverpool (A) - 4,Man Utd (H) - 4,3.6
Bournemouth,Man City (A) - 5,Everton (H) - 3,Newcastle (A) - 3,Brentford (H) - 3,Liverpool (H) - 4,3.6

In [53]:
# Create a short name mapping for teams
team_short_names = {
    "Arsenal": "ARS",
    "Aston Villa": "AVL",
    "Bournemouth": "BOU",
    "Brentford": "BRE",
    "Brighton": "BHA",
    "Chelsea": "CHE",
    "Coventry City": "COV",
    "Crystal Palace": "CRY",
    "Everton": "EVE",
    "Fulham": "FUL",
    "Hull City": "HUL",
    "Ipswich Town": "IPS",
    "Leeds": "LEE",
    "Liverpool": "LIV",
    "Man City": "MCI",
    "Man Utd": "MUN",
    "Newcastle": "NEW",
    "Nott'm Forest": "NFO",
    "Spurs": "TOT",
    "Sunderland": "SUN"
}

# Convert full opponent names in the fixture table to short names
for column in ["GW1", "GW2", "GW3", "GW4", "GW5"]:
    
    fixture_table[column] = fixture_table[column].apply(
        lambda x: (
            team_short_names.get(
                x.rsplit(" (", 1)[0].split(" - ")[0],
                x.rsplit(" (", 1)[0].split(" - ")[0]
            )
            + " (" 
            + x.rsplit("(", 1)[1].split(")", 1)[0]
            + ")"
        )
    )

# Add fixture rating based on average difficulty
def get_fixture_rating(avg_difficulty):
    if avg_difficulty <= 2.5:
        return "Excellent"
    elif avg_difficulty <= 3.0:
        return "Good"
    elif avg_difficulty <= 3.5:
        return "Average"
    elif avg_difficulty <= 4.0:
        return "Difficult"
    else:
        return "Very Difficult"


fixture_table["Rating"] = fixture_table["Avg Difficulty"].apply(
    get_fixture_rating
)

fixture_table

,GW1,GW2,GW3,GW4,GW5,Avg Difficulty,Rating
team,,,,,,,
Liverpool,NEW (A),NFO (H),IPS (A),FUL (H),BOU (A),2.6,Good
Man City,BOU (H),CRY (A),COV (H),MUN (A),SUN (H),2.8,Good
Man Utd,HUL (A),IPS (H),EVE (A),MCI (H),FUL (A),2.8,Good
Leeds,NFO (A),BRE (H),BHA (A),NEW (H),CRY (H),2.8,Good
Spurs,BRE (A),NEW (H),NFO (A),EVE (H),AVL (H),2.8,Good
Aston Villa,BHA (A),ARS (H),HUL (A),NFO (H),TOT (A),3.0,Good
Chelsea,FUL (A),BHA (H),ARS (A),HUL (H),BRE (A),3.0,Good
Brentford,TOT (H),LEE (A),SUN (H),BOU (A),CHE (H),3.0,Good
Everton,CRY (H),BOU (A),MUN (H),TOT (A),IPS (H),3.0,Good
Crystal Palace,EVE (A),MCI (H),FUL (A),IPS (H),LEE (A),3.0,Good
Newcastle,LIV (H),TOT (A),BOU (H),LEE (A),HUL (H),3.0,Good
Brighton,AVL (H),CHE (A),LEE (H),COV (A),ARS (H),3.0,Good
Nott'm Forest,LEE (H),LIV (A),TOT (H),AVL (A),COV (H),3.0,Good
Ipswich Town,SUN (H),MUN (A),LIV (H),CRY (A),EVE (A),3.2,Average
Arsenal,COV (H),AVL (A),CHE (H),SUN (A),BHA (A),3.2,Average
Hull City,MUN (H),COV (A),AVL (H),CHE (A),NEW (A),3.2,Average
Sunderland,IPS (A),FUL (H),BRE (A),ARS (H),MCI (A),3.2,Average
Coventry City,ARS (A),HUL (H),MCI (A),BHA (H),NFO (A),3.4,Average
Fulham,CHE (H),SUN (A),CRY (H),LIV (A),MUN (H),3.6,Difficult
Bournemouth,MCI (A),EVE (H),NEW (A),BRE (H),LIV (H),3.6,Difficult

In [55]:
print(next_5_detailed.columns.tolist())

['team', 'event', 'fixture', 'difficulty', 'average_difficulty', 'fixture_with_rating']

In [56]:
# Short names for teams
team_short_names = {
    "Arsenal": "ARS",
    "Aston Villa": "AVL",
    "Bournemouth": "BOU",
    "Brentford": "BRE",
    "Brighton": "BHA",
    "Chelsea": "CHE",
    "Coventry City": "COV",
    "Crystal Palace": "CRY",
    "Everton": "EVE",
    "Fulham": "FUL",
    "Leeds": "LEE",
    "Liverpool": "LIV",
    "Man City": "MCI",
    "Man Utd": "MUN",
    "Newcastle": "NEW",
    "Nott'm Forest": "NFO",
    "Spurs": "TOT",
    "Sunderland": "SUN"
}

# Take the first 5 fixtures for every team
next_5_display = (
    team_fixtures
    .groupby("team", group_keys=False)
    .head(5)
    .copy()
)

# Create short opponent names
next_5_display["short_opponent"] = (
    next_5_display["opponent"].map(team_short_names)
)

# Create Home/Away indicator
next_5_display["venue"] = (
    next_5_display["is_home"]
    .map({True: "H", False: "A"})
)

# Create the fixture display with individual FDR
next_5_display["fixture_display"] = (
    next_5_display["short_opponent"]
    + " ("
    + next_5_display["venue"]
    + ") - "
    + next_5_display["difficulty"].astype(str)
)

# Turn gameweeks into columns
fixture_table = next_5_display.pivot(
    index="team",
    columns="event",
    values="fixture_display"
)

# Rename event columns to GW columns
fixture_table.columns = [
    f"GW{gw}" for gw in fixture_table.columns
]

# Add average FDR for the 5 fixtures
fixture_table["Avg Difficulty"] = (
    next_5_display
    .groupby("team")["difficulty"]
    .mean()
    .round(2)
)

# Function for overall fixture rating
def get_fixture_rating(avg_difficulty):
    if avg_difficulty <= 2.5:
        return "Excellent"
    elif avg_difficulty <= 3.0:
        return "Good"
    elif avg_difficulty <= 3.5:
        return "Average"
    elif avg_difficulty <= 4.0:
        return "Difficult"
    else:
        return "Very Difficult"

# Add overall rating
fixture_table["Rating"] = (
    fixture_table["Avg Difficulty"]
    .apply(get_fixture_rating)
)

# Sort from easiest fixtures to hardest
fixture_table = fixture_table.sort_values(
    "Avg Difficulty"
)

fixture_table

,GW1,GW2,GW3,GW4,GW5,Avg Difficulty,Rating
team,,,,,,,
Liverpool,NEW (A) - 3,NFO (H) - 3,NaN,FUL (H) - 2,BOU (A) - 3,2.6,Good
Man City,BOU (H) - 3,CRY (A) - 3,COV (H) - 2,MUN (A) - 4,SUN (H) - 2,2.8,Good
Man Utd,NaN,NaN,EVE (A) - 3,MCI (H) - 4,FUL (A) - 3,2.8,Good
Leeds,NFO (A) - 3,BRE (H) - 3,BHA (A) - 3,NEW (H) - 2,CRY (H) - 3,2.8,Good
Spurs,BRE (A) - 3,NEW (H) - 2,NFO (A) - 3,EVE (H) - 3,AVL (H) - 3,2.8,Good
Aston Villa,BHA (A) - 3,ARS (H) - 4,NaN,NFO (H) - 3,TOT (A) - 3,3.0,Good
Chelsea,FUL (A) - 3,BHA (H) - 2,ARS (A) - 5,NaN,BRE (A) - 3,3.0,Good
Brentford,TOT (H) - 3,LEE (A) - 3,SUN (H) - 2,BOU (A) - 3,CHE (H) - 4,3.0,Good
Everton,CRY (H) - 3,BOU (A) - 3,MUN (H) - 4,TOT (A) - 3,NaN,3.0,Good
Crystal Palace,EVE (A) - 3,MCI (H) - 4,FUL (A) - 3,NaN,LEE (A) - 3,3.0,Good
Newcastle,LIV (H) - 4,TOT (A) - 3,BOU (H) - 3,LEE (A) - 3,NaN,3.0,Good
Brighton,AVL (H) - 3,CHE (A) - 4,LEE (H) - 2,COV (A) - 2,ARS (H) - 4,3.0,Good
Nott'm Forest,LEE (H) - 2,LIV (A) - 4,TOT (H) - 3,AVL (A) - 4,COV (H) - 2,3.0,Good
Ipswich Town,SUN (H) - 2,MUN (A) - 4,LIV (H) - 4,CRY (A) - 3,EVE (A) - 3,3.2,Average
Arsenal,COV (H) - 2,AVL (A) - 4,CHE (H) - 4,SUN (A) - 3,BHA (A) - 3,3.2,Average
Hull City,MUN (H) - 4,COV (A) - 2,AVL (H) - 3,CHE (A) - 4,NEW (A) - 3,3.2,Average
Sunderland,NaN,FUL (H) - 2,BRE (A) - 3,ARS (H) - 4,MCI (A) - 5,3.2,Average
Coventry City,ARS (A) - 5,NaN,MCI (A) - 5,BHA (H) - 2,NFO (A) - 3,3.4,Average
Fulham,CHE (H) - 4,SUN (A) - 3,CRY (H) - 3,LIV (A) - 4,MUN (H) - 4,3.6,Difficult
Bournemouth,MCI (A) - 5,EVE (H) - 3,NEW (A) - 3,BRE (H) - 3,LIV (H) - 4,3.6,Difficult

In [57]:
fixture_table = fixture_table.fillna("-")

fixture_table

,GW1,GW2,GW3,GW4,GW5,Avg Difficulty,Rating
team,,,,,,,
Liverpool,NEW (A) - 3,NFO (H) - 3,-,FUL (H) - 2,BOU (A) - 3,2.6,Good
Man City,BOU (H) - 3,CRY (A) - 3,COV (H) - 2,MUN (A) - 4,SUN (H) - 2,2.8,Good
Man Utd,-,-,EVE (A) - 3,MCI (H) - 4,FUL (A) - 3,2.8,Good
Leeds,NFO (A) - 3,BRE (H) - 3,BHA (A) - 3,NEW (H) - 2,CRY (H) - 3,2.8,Good
Spurs,BRE (A) - 3,NEW (H) - 2,NFO (A) - 3,EVE (H) - 3,AVL (H) - 3,2.8,Good
Aston Villa,BHA (A) - 3,ARS (H) - 4,-,NFO (H) - 3,TOT (A) - 3,3.0,Good
Chelsea,FUL (A) - 3,BHA (H) - 2,ARS (A) - 5,-,BRE (A) - 3,3.0,Good
Brentford,TOT (H) - 3,LEE (A) - 3,SUN (H) - 2,BOU (A) - 3,CHE (H) - 4,3.0,Good
Everton,CRY (H) - 3,BOU (A) - 3,MUN (H) - 4,TOT (A) - 3,-,3.0,Good
Crystal Palace,EVE (A) - 3,MCI (H) - 4,FUL (A) - 3,-,LEE (A) - 3,3.0,Good
Newcastle,LIV (H) - 4,TOT (A) - 3,BOU (H) - 3,LEE (A) - 3,-,3.0,Good
Brighton,AVL (H) - 3,CHE (A) - 4,LEE (H) - 2,COV (A) - 2,ARS (H) - 4,3.0,Good
Nott'm Forest,LEE (H) - 2,LIV (A) - 4,TOT (H) - 3,AVL (A) - 4,COV (H) - 2,3.0,Good
Ipswich Town,SUN (H) - 2,MUN (A) - 4,LIV (H) - 4,CRY (A) - 3,EVE (A) - 3,3.2,Average
Arsenal,COV (H) - 2,AVL (A) - 4,CHE (H) - 4,SUN (A) - 3,BHA (A) - 3,3.2,Average
Hull City,MUN (H) - 4,COV (A) - 2,AVL (H) - 3,CHE (A) - 4,NEW (A) - 3,3.2,Average
Sunderland,-,FUL (H) - 2,BRE (A) - 3,ARS (H) - 4,MCI (A) - 5,3.2,Average
Coventry City,ARS (A) - 5,-,MCI (A) - 5,BHA (H) - 2,NFO (A) - 3,3.4,Average
Fulham,CHE (H) - 4,SUN (A) - 3,CRY (H) - 3,LIV (A) - 4,MUN (H) - 4,3.6,Difficult
Bournemouth,MCI (A) - 5,EVE (H) - 3,NEW (A) - 3,BRE (H) - 3,LIV (H) - 4,3.6,Difficult

In [58]:
next_5_display["opponent"].map(team_short_names)

0      COV
399    AVL
29     CHE
416    SUN
422    BHA
      ...
383    NaN
17     FUL
402    BRE
36     ARS
425    MCI
Name: opponent, Length: 100, dtype: str

In [59]:
team_short_names.update({
    "Hull City": "HUL",
    "Ipswich Town": "IPS",
    "Coventry City": "COV"
})

In [60]:
next_5_display["short_opponent"] = (
    next_5_display["opponent"].map(team_short_names)
)

next_5_display["venue"] = (
    next_5_display["is_home"]
    .map({True: "H", False: "A"})
)

next_5_display["fixture_display"] = (
    next_5_display["short_opponent"]
    + " ("
    + next_5_display["venue"]
    + ") - "
    + next_5_display["difficulty"].astype(str)
)

In [61]:
fixture_table = next_5_display.pivot(
    index="team",
    columns="event",
    values="fixture_display"
)

fixture_table.columns = [
    f"GW{gw}" for gw in fixture_table.columns
]

fixture_table["Avg Difficulty"] = (
    next_5_display
    .groupby("team")["difficulty"]
    .mean()
    .round(2)
)

fixture_table["Rating"] = (
    fixture_table["Avg Difficulty"]
    .apply(get_fixture_rating)
)

fixture_table = fixture_table.sort_values("Avg Difficulty")

fixture_table

,GW1,GW2,GW3,GW4,GW5,Avg Difficulty,Rating
team,,,,,,,
Liverpool,NEW (A) - 3,NFO (H) - 3,IPS (A) - 2,FUL (H) - 2,BOU (A) - 3,2.6,Good
Man City,BOU (H) - 3,CRY (A) - 3,COV (H) - 2,MUN (A) - 4,SUN (H) - 2,2.8,Good
Man Utd,HUL (A) - 2,IPS (H) - 2,EVE (A) - 3,MCI (H) - 4,FUL (A) - 3,2.8,Good
Leeds,NFO (A) - 3,BRE (H) - 3,BHA (A) - 3,NEW (H) - 2,CRY (H) - 3,2.8,Good
Spurs,BRE (A) - 3,NEW (H) - 2,NFO (A) - 3,EVE (H) - 3,AVL (H) - 3,2.8,Good
Aston Villa,BHA (A) - 3,ARS (H) - 4,HUL (A) - 2,NFO (H) - 3,TOT (A) - 3,3.0,Good
Chelsea,FUL (A) - 3,BHA (H) - 2,ARS (A) - 5,HUL (H) - 2,BRE (A) - 3,3.0,Good
Brentford,TOT (H) - 3,LEE (A) - 3,SUN (H) - 2,BOU (A) - 3,CHE (H) - 4,3.0,Good
Everton,CRY (H) - 3,BOU (A) - 3,MUN (H) - 4,TOT (A) - 3,IPS (H) - 2,3.0,Good
Crystal Palace,EVE (A) - 3,MCI (H) - 4,FUL (A) - 3,IPS (H) - 2,LEE (A) - 3,3.0,Good
Newcastle,LIV (H) - 4,TOT (A) - 3,BOU (H) - 3,LEE (A) - 3,HUL (H) - 2,3.0,Good
Brighton,AVL (H) - 3,CHE (A) - 4,LEE (H) - 2,COV (A) - 2,ARS (H) - 4,3.0,Good
Nott'm Forest,LEE (H) - 2,LIV (A) - 4,TOT (H) - 3,AVL (A) - 4,COV (H) - 2,3.0,Good
Ipswich Town,SUN (H) - 2,MUN (A) - 4,LIV (H) - 4,CRY (A) - 3,EVE (A) - 3,3.2,Average
Arsenal,COV (H) - 2,AVL (A) - 4,CHE (H) - 4,SUN (A) - 3,BHA (A) - 3,3.2,Average
Hull City,MUN (H) - 4,COV (A) - 2,AVL (H) - 3,CHE (A) - 4,NEW (A) - 3,3.2,Average
Sunderland,IPS (A) - 2,FUL (H) - 2,BRE (A) - 3,ARS (H) - 4,MCI (A) - 5,3.2,Average
Coventry City,ARS (A) - 5,HUL (H) - 2,MCI (A) - 5,BHA (H) - 2,NFO (A) - 3,3.4,Average
Fulham,CHE (H) - 4,SUN (A) - 3,CRY (H) - 3,LIV (A) - 4,MUN (H) - 4,3.6,Difficult
Bournemouth,MCI (A) - 5,EVE (H) - 3,NEW (A) - 3,BRE (H) - 3,LIV (H) - 4,3.6,Difficult

In [62]:
next_5_display["fixture_display"] = (
    next_5_display["short_opponent"]
    + " ("
    + next_5_display["venue"]
    + ")\n"
    + next_5_display["difficulty"].astype(str)
)

In [68]:
from IPython.display import display

# Create fixture display with opponent, home/away, and difficulty
next_5_display["fixture_display"] = (
    next_5_display["short_opponent"]
    + " ("
    + next_5_display["venue"]
    + ")"
    + "\n"
    + next_5_display["difficulty"].astype(str)
)

# Create the fixture table with gameweeks as columns
fixture_table = next_5_display.pivot(
    index="team",
    columns="event",
    values="fixture_display"
)

# Rename gameweek columns
fixture_table.columns = [
    f"GW{gw}" for gw in fixture_table.columns
]

# Calculate average difficulty for each team
fixture_table["Avg Difficulty"] = (
    next_5_display
    .groupby("team")["difficulty"]
    .mean()
)

# # Create overall fixture rating
# def get_fixture_rating(avg_difficulty):
#     if avg_difficulty <= 2.5:
#         return "Excellent"
#     elif avg_difficulty <= 3.0:
#         return "Good"
#     elif avg_difficulty <= 3.5:
#         return "Average"
#     elif avg_difficulty <= 4.0:
#         return "Difficult"
#     else:
#         return "Very Difficult"


# # Add rating column
# fixture_table["Rating"] = (
#     fixture_table["Avg Difficulty"]
#     .apply(get_fixture_rating)
# )

# Sort from easiest fixtures to hardest
fixture_table = fixture_table.sort_values(
    "Avg Difficulty"
)

# Display the table
styled_fixture_table = (
    fixture_table.style
    .format({
        "Avg Difficulty": "{:.1f}"
    })
    .set_properties(
        subset=["GW1", "GW2", "GW3", "GW4", "GW5"],
        **{
            "white-space": "pre-line",
            "text-align": "center"
        }
    )
)

display(styled_fixture_table)

In [70]:
%whos

Variable                 Type         Data/Info
-----------------------------------------------
arsenal_average_fdr      float64      3.2
arsenal_fixtures         DataFrame    Shape: (5, 7)
arsenal_next_5           DataFrame    Shape: (5, 3)
availability_fields      list         n=2
away_fixtures            DataFrame    Shape: (380, 7)
column                   str          GW5
data                     dict         n=10
display                  function     <function display at 0x000001A96F06B100>
expected_stats_fields    list         n=3
field                    str          cost_change_event
fixture_ratings          DataFrame    Shape: (20, 3)
fixture_table            DataFrame    Shape: (20, 6)
fixtures                 list         n=380
fixtures_df              DataFrame    Shape: (380, 17)
fixtures_named           DataFrame    Shape: (380, 19)
fixtures_url             str          https://fantasy.premierleague.com/api/fixtures/
gameweek_1               DataFrame    Shape: (10, 17)
get_fixture_rating       function     <function get_fixture_rat<...>ng at 0x000001A902572340>
gw_columns               list         n=5
home_fixtures            DataFrame    Shape: (380, 7)
ict_fields               list         n=4
identity_fields          list         n=4
important_fields         list         n=28
next_5_detailed          DataFrame    Shape: (100, 6)
next_5_display           DataFrame    Shape: (100, 11)
ownership                str          37.9
pd                       module       <module 'pandas' from 'C:<...>es\\pandas\\__init__.py'>
performance_fields       list         n=7
price                    float        6.0
price_change_fields      list         n=2
price_ownership_fields   list         n=2
requests                 module       <module 'requests' from '<...>\\requests\\__init__.py'>
response                 Response     <Response [200]>
styled_fixture_table     Styler       <pandas.io.formats.style.<...>ct at 0x000001A903F941D0>
team_fixtures            DataFrame    Shape: (760, 8)
team_mapping             DataFrame    Shape: (20, 2)
team_position_fields     list         n=2
team_short_names         dict         n=20
teams_df                 DataFrame    Shape: (20, 22)
transfer_fields          list         n=2
url                      str          https://fantasy.premierle<...>com/api/bootstrap-static/
varsenal_next_5          DataFrame    Shape: (5, 3)

In [71]:
players_df = pd.DataFrame(data["elements"])

In [72]:
players_df[
    ["id", "web_name", "team", "now_cost", "total_points"]
].head(10)

   id      web_name  team  now_cost  total_points
0   1          Raya     1        60             6
1   2  Arrizabalaga     1        50             0
2   3       Meslier     1        50             0
3   4       Gabriel     1        80             5
4   5      J.Timber     1        65             0
5   6        Saliba     1        60             0
6   7  Lewis-Skelly     1        55             3
7   8     Calafiori     1        55             9
8   9      Hincapie     1        55             1
9  10         White     1        55            11

In [73]:
players_df[
    players_df["web_name"] == "Saka"
][
    ["id", "web_name", "team", "now_cost", "total_points"]
]

    id web_name  team  now_cost  total_points
11  12     Saka     1        95             9

In [74]:
player_id = 12

player_history_url = (
    f"https://fantasy.premierleague.com/api/element-summary/{player_id}/"
)

response = requests.get(player_history_url)

player_data = response.json()

In [75]:
player_data.keys()

dict_keys(['fixtures', 'history', 'history_past'])

In [76]:
history_df = pd.DataFrame(player_data["history"])

history_df.head()

,element,fixture,opponent_team,total_points,was_home,kickoff_time,team_h_score,team_a_score,round,modified,...,starts,expected_goals,expected_assists,expected_goal_involvements,expected_goals_conceded,value,transfers_balance,selected,transfers_in,transfers_out
0,12,1,7,9,True,2026-08-21T19:00:00Z,3,0,1,False,...,1,0.64,0.08,0.72,0.06,95,0,819914,0,0

In [77]:
history_df.columns.tolist()

['element',
 'fixture',
 'opponent_team',
 'total_points',
 'was_home',
 'kickoff_time',
 'team_h_score',
 'team_a_score',
 'round',
 'modified',
 'minutes',
 'goals_scored',
 'assists',
 'clean_sheets',
 'goals_conceded',
 'own_goals',
 'penalties_saved',
 'penalties_missed',
 'yellow_cards',
 'red_cards',
 'saves',
 'bonus',
 'bps',
 'influence',
 'creativity',
 'threat',
 'ict_index',
 'clearances_blocks_interceptions',
 'recoveries',
 'tackles',
 'defensive_contribution',
 'starts',
 'expected_goals',
 'expected_assists',
 'expected_goal_involvements',
 'expected_goals_conceded',
 'value',
 'transfers_balance',
 'selected',
 'transfers_in',
 'transfers_out']

In [78]:
important_history_fields = [
    "element",
    "fixture",
    "opponent_team",
    "total_points",
    "was_home",
    "kickoff_time",
    "round",
    "minutes",
    "goals_scored",
    "assists",
    "clean_sheets",
    "bonus",
    "bps",
    "value",
    "transfers_balance",
    "selected",
    "expected_goals",
    "expected_assists",
    "expected_goal_involvements"
]

history_df[important_history_fields]

,element,fixture,opponent_team,total_points,was_home,kickoff_time,round,minutes,goals_scored,assists,clean_sheets,bonus,bps,value,transfers_balance,selected,expected_goals,expected_assists,expected_goal_involvements
0,12,1,7,9,True,2026-08-21T19:00:00Z,1,67,1,0,1,1,36,95,0,819914,0.64,0.08,0.72

In [80]:
history_past_df = pd.DataFrame(
    player_data["history_past"]
)

history_past_df

,season_name,element_code,start_cost,end_cost,total_points,minutes,goals_scored,assists,clean_sheets,goals_conceded,...,ict_index,clearances_blocks_interceptions,recoveries,tackles,defensive_contribution,starts,expected_goals,expected_assists,expected_goal_involvements,expected_goals_conceded
0,2018/19,223340,45,45,1,7,0,0,0,0,...,0.0,0,0,0,0,0,0.00,0.00,0.00,0.00
1,2019/20,223340,45,47,71,1746,1,6,7,18,...,89.8,0,0,0,0,0,0.00,0.00,0.00,0.00
2,2020/21,223340,55,51,114,2554,5,5,8,31,...,212.7,0,0,0,0,0,0.00,0.00,0.00,0.00
3,2021/22,223340,65,67,179,2978,11,9,13,39,...,320.0,0,0,0,0,0,0.00,0.00,0.00,0.00
4,2022/23,223340,80,80,202,3183,14,12,12,42,...,333.4,0,0,0,0,37,11.49,5.97,17.46,39.66
5,2023/24,223340,85,88,226,2922,16,12,16,27,...,375.7,0,0,0,0,35,15.40,10.90,26.29,25.66
6,2024/25,223340,100,104,127,1724,6,11,7,21,...,227.9,0,0,0,108,20,6.87,7.78,14.65,17.72
7,2025/26,223340,100,100,157,2218,7,10,12,16,...,230.6,28,116,40,184,25,7.57,7.16,14.73,15.57

In [81]:
history_df = pd.DataFrame(player_data["history"])

In [82]:
player_fixtures_df = pd.DataFrame(
    player_data["fixtures"]
)

player_fixtures_df.head()

,id,code,team_h,team_h_score,team_a,team_a_score,event,finished,minutes,provisional_start_time,kickoff_time,event_name,is_home,difficulty
0,20,2645206,2,None,1,None,2,False,0,False,2026-08-31T19:00:00Z,Gameweek 2,False,4
1,29,2645215,1,None,6,None,3,False,0,False,2026-09-06T15:30:00Z,Gameweek 3,True,4
2,36,2645233,20,None,1,None,4,False,0,False,2026-09-12T19:00:00Z,Gameweek 4,False,3
3,42,2645237,5,None,1,None,5,False,0,False,2026-09-19T14:00:00Z,Gameweek 5,False,3
4,51,2645245,1,None,13,None,6,False,0,False,2026-10-10T11:30:00Z,Gameweek 6,True,2

In [89]:
past_stats = history_past_df[
    [
        "season_name",
        "total_points",
        "minutes",
        "goals_scored",
        "assists",
        "clean_sheets",
        "bonus",
        "bps",
        "expected_goals",
        "expected_assists",
        "expected_goal_involvements"
    ]
]

past_stats

,season_name,total_points,minutes,goals_scored,assists,clean_sheets,bonus,bps,expected_goals,expected_assists,expected_goal_involvements
0,2018/19,1,7,0,0,0,0,3,0.00,0.00,0.00
1,2019/20,71,1746,1,6,7,4,259,0.00,0.00,0.00
2,2020/21,114,2554,5,5,8,8,414,0.00,0.00,0.00
3,2021/22,179,2978,11,9,13,18,566,0.00,0.00,0.00
4,2022/23,202,3183,14,12,12,19,678,11.49,5.97,17.46
5,2023/24,226,2922,16,12,16,29,776,15.40,10.90,26.29
6,2024/25,127,1724,6,11,7,18,508,6.87,7.78,14.65
7,2025/26,157,2218,7,10,12,18,570,7.57,7.16,14.73

In [86]:
%pip install understatapi

Collecting understatapi
  Downloading understatapi-0.7.1.tar.gz (537 kB)
     ---------------------------------------- 0.0/537.7 kB ? eta -:--:--
      --------------------------------------- 10.2/537.7 kB ? eta -:--:--
     - ----------------------------------- 20.5/537.7 kB 217.9 kB/s eta 0:00:03
     --- --------------------------------- 51.2/537.7 kB 372.4 kB/s eta 0:00:02
     --------- -------------------------- 143.4/537.7 kB 774.0 kB/s eta 0:00:01
     --------------- ---------------------- 225.3/537.7 kB 1.1 MB/s eta 0:00:01
     -------------------------- ----------- 368.6/537.7 kB 1.4 MB/s eta 0:00:01
     ----------------------------------- -- 501.8/537.7 kB 1.7 MB/s eta 0:00:01
     -------------------------------------- 537.7/537.7 kB 1.6 MB/s eta 0:00:00
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'done'
Collecting certifi==2025.11.12 (from understatapi)
  Using cached certifi-2025.11.12-py3-none-any.whl.metadata (2.5 kB)
Collecting charset-normalizer==3.4.4 (from understatapi)
  Using cached charset_normalizer-3.4.4-cp311-cp311-win_amd64.whl.metadata (38 kB)
Collecting idna==2.10 (from understatapi)
  Downloading idna-2.10-py2.py3-none-any.whl.metadata (9.1 kB)
Collecting requests==2.32.5 (from understatapi)
  Using cached requests-2.32.5-py3-none-any.whl.metadata (4.9 kB)
Collecting urllib3==1.26.5 (from understatapi)
  Downloading urllib3-1.26.5-py2.py3-none-any.whl.metadata (43 kB)
     ---------------------------------------- 0.0/43.7 kB ? eta -:--:--
     ---------------------------------------- 43.7/43.7 kB 2.2 MB/s eta 0:00:00
Using cached certifi-2025.11.12-py3-none-any.whl (159 kB)
Using cached charset_normalizer-3.4.4-cp311-cp311-win_amd64.whl (106 kB)
Downloading idna-2.10-py2.py3-none-any.whl (58 kB)
   ---------------------------------------- 0.0/58.8 kB ? eta -:--:--
   ---------------------------------------- 58.8/58.8 kB 3.2 MB/s eta 0:00:00
Using cached requests-2.32.5-py3-none-any.whl (64 kB)
Downloading urllib3-1.26.5-py2.py3-none-any.whl (138 kB)
   ---------------------------------------- 0.0/138.1 kB ? eta -:--:--
   -------------------------------------- - 133.1/138.1 kB 4.0 MB/s eta 0:00:01
   ---------------------------------------- 138.1/138.1 kB 2.7 MB/s eta 0:00:00
Building wheels for collected packages: understatapi
  Building wheel for understatapi (pyproject.toml): started
  Building wheel for understatapi (pyproject.toml): finished with status 'done'
  Created wheel for understatapi: filename=understatapi-0.7.1-py3-none-any.whl size=15474 sha256=68b61d599d77d8493b85eb9626cbdbc1e7d6c5a9ad15b53eec4e2418b761ea76
  Stored in directory: c:\users\manas\appdata\local\pip\cache\wheels\a0\6a\c6\e5f4bc020ff8d84046876f7757e949141be98bad3b794eaf26
Successfully built understatapi
Installing collected packages: urllib3, idna, charset-normalizer, certifi, requests, understatapi
  Attempting uninstall: urllib3
    Found existing installation: urllib3 2.7.0
    Uninstalling urllib3-2.7.0:
      Successfully uninstalled urllib3-2.7.0
  Attempting uninstall: idna
    Found existing installation: idna 3.19
    Uninstalling idna-3.19:
      Successfully uninstalled idna-3.19
  Attempting uninstall: charset-normalizer
    Found existing installation: charset-normalizer 3.5.1
    Uninstalling charset-normalizer-3.5.1:
      Successfully uninstalled charset-normalizer-3.5.1
  Attempting uninstall: certifi
    Found existing installation: certifi 2026.7.22
    Uninstalling certifi-2026.7.22:
      Successfully uninstalled certifi-2026.7.22
  Attempting uninstall: requests
    Found existing installation: requests 2.34.2
    Uninstalling requests-2.34.2:
      Successfully uninstalled requests-2.34.2
Successfully installed certifi-2025.11.12 charset-normalizer-3.4.4 idna-2.10 requests-2.32.5 understatapi-0.7.1 urllib3-1.26.5
Note: you may need to restart the kernel to use updated packages.

  WARNING: Failed to remove contents in a temporary directory 'C:\Users\manas\Downloads\FPL-Edge\venv\Lib\site-packages\~harset_normalizer'.
  You can safely remove it manually.

[notice] A new release of pip is available: 24.0 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [87]:
from understatapi import UnderstatClient

In [88]:
from understatapi import UnderstatClient

with UnderstatClient() as understat:
    player_data_2019 = (
        understat
        .league(league="EPL")
        .get_player_data(season="2019")
    )

In [90]:
player_fixtures_df = pd.DataFrame(
    player_data["fixtures"]
)

player_fixtures_df.head()

,id,code,team_h,team_h_score,team_a,team_a_score,event,finished,minutes,provisional_start_time,kickoff_time,event_name,is_home,difficulty
0,20,2645206,2,None,1,None,2,False,0,False,2026-08-31T19:00:00Z,Gameweek 2,False,4
1,29,2645215,1,None,6,None,3,False,0,False,2026-09-06T15:30:00Z,Gameweek 3,True,4
2,36,2645233,20,None,1,None,4,False,0,False,2026-09-12T19:00:00Z,Gameweek 4,False,3
3,42,2645237,5,None,1,None,5,False,0,False,2026-09-19T14:00:00Z,Gameweek 5,False,3
4,51,2645245,1,None,13,None,6,False,0,False,2026-10-10T11:30:00Z,Gameweek 6,True,2

In [91]:
player_fixture_display = player_fixtures_df.merge(
    teams_df[["id", "name"]],
    left_on="team_h",
    right_on="id",
    how="left"
)

player_fixture_display = player_fixture_display.rename(
    columns={"name": "home_team"}
).drop(columns=["id_y"])

player_fixture_display = player_fixture_display.merge(
    teams_df[["id", "name"]],
    left_on="team_a",
    right_on="id",
    how="left"
)

player_fixture_display = player_fixture_display.rename(
    columns={"name": "away_team"}
).drop(columns=["id"])

player_fixture_display[
    [
        "event",
        "home_team",
        "away_team",
        "is_home",
        "difficulty",
        "kickoff_time",
        "finished"
    ]
].head(10)

,event,home_team,away_team,is_home,difficulty,kickoff_time,finished
0,2,Aston Villa,Arsenal,False,4,2026-08-31T19:00:00Z,False
1,3,Arsenal,Chelsea,True,4,2026-09-06T15:30:00Z,False
2,4,Sunderland,Arsenal,False,3,2026-09-12T19:00:00Z,False
3,5,Brighton,Arsenal,False,3,2026-09-19T14:00:00Z,False
4,6,Arsenal,Leeds,True,2,2026-10-10T11:30:00Z,False
5,7,Nott'm Forest,Arsenal,False,3,2026-10-18T15:30:00Z,False
6,8,Arsenal,Everton,True,3,2026-10-24T14:00:00Z,False
7,9,Liverpool,Arsenal,False,4,2026-11-01T16:30:00Z,False
8,10,Arsenal,Hull City,True,2,2026-11-07T15:00:00Z,False
9,11,Newcastle,Arsenal,False,3,2026-11-21T15:00:00Z,False

In [92]:
history_df[
    [
        "element",
        "round",
        "total_points",
        "minutes",
        "goals_scored",
        "assists"
    ]
]

   element  round  total_points  minutes  goals_scored  assists
0       12      1             9       67             1        0

In [93]:
player_mapping = players_df[["id", "web_name"]]

In [94]:
history_with_names = history_df.merge(
    player_mapping,
    left_on="element",
    right_on="id",
    how="left"
)

In [95]:
history_with_names[
    [
        "web_name",
        "element",
        "round",
        "total_points",
        "minutes",
        "goals_scored",
        "assists"
    ]
]

  web_name  element  round  total_points  minutes  goals_scored  assists
0     Saka       12      1             9       67             1        0

In [96]:
identity_fields = [
    "element",
    "round"
]

In [97]:
performance_fields = [
    "total_points",
    "minutes",
    "goals_scored",
    "assists",
    "clean_sheets",
    "goals_conceded",
    "yellow_cards",
    "red_cards",
    "bonus",
    "bps"
]

In [98]:
expected_stats_fields = [
    "expected_goals",
    "expected_assists",
    "expected_goal_involvements",
    "expected_goals_conceded"
]

In [99]:
ict_fields = [
    "influence",
    "creativity",
    "threat",
    "ict_index"
]

In [106]:
important_fields = (
    identity_fields
    + performance_fields
    + expected_stats_fields
    + ict_fields
)

history_with_names[
    ["web_name"] + important_fields
]

,web_name,element,round,total_points,minutes,goals_scored,assists,clean_sheets,goals_conceded,yellow_cards,red_cards,bonus,bps,expected_goals,expected_assists,expected_goal_involvements,expected_goals_conceded,influence,creativity,threat,ict_index
0,Saka,12,1,9,67,1,0,1,0,0,0,1,36,0.64,0.08,0.72,0.06,42.8,26.1,33.0,10.2

In [101]:
pd.set_option("display.max_columns", None)

In [105]:
history_with_names[
    ["web_name"] + important_fields
]

,web_name,element,round,total_points,minutes,goals_scored,assists,clean_sheets,goals_conceded,yellow_cards,red_cards,bonus,bps,expected_goals,expected_assists,expected_goal_involvements,expected_goals_conceded,influence,creativity,threat,ict_index
0,Saka,12,1,9,67,1,0,1,0,0,0,1,36,0.64,0.08,0.72,0.06,42.8,26.1,33.0,10.2

In [104]:
pd.set_option("display.max_columns", None)
pd.set_option("display.width", None)

In [107]:
players_df[
    players_df["web_name"].isin(
        ["Saka", "Haaland"]
    )
][["id", "web_name"]]

      id web_name
11    12     Saka
456  411  Haaland

In [108]:
player_ids = [12, 411]

all_player_histories = []

for player_id in player_ids:
    
    player_history_url = (
        f"https://fantasy.premierleague.com/api/element-summary/{player_id}/"
    )
    
    response = requests.get(player_history_url)
    player_data = response.json()
    
    player_history = pd.DataFrame(player_data["history"])
    
    all_player_histories.append(player_history)


combined_history_df = pd.concat(
    all_player_histories,
    ignore_index=True
)

combined_history_df.head()

,element,fixture,opponent_team,total_points,was_home,kickoff_time,team_h_score,team_a_score,round,modified,minutes,goals_scored,assists,clean_sheets,goals_conceded,own_goals,penalties_saved,penalties_missed,yellow_cards,red_cards,saves,bonus,bps,influence,creativity,threat,ict_index,clearances_blocks_interceptions,recoveries,tackles,defensive_contribution,starts,expected_goals,expected_assists,expected_goal_involvements,expected_goals_conceded,value,transfers_balance,selected,transfers_in,transfers_out
0,12,1,7,9,True,2026-08-21T19:00:00Z,3,0,1,False,67,1,0,1,0,0,0,0,0,0,0,1,36,42.8,26.1,33.0,10.2,2,4,1,7,1,0.64,0.08,0.72,0.06,95,0,819914,0,0
1,411,8,3,2,True,2026-08-23T13:00:00Z,2,1,1,False,90,0,0,0,1,0,0,0,0,0,0,0,6,3.8,5.2,50.0,5.9,0,3,0,3,1,0.74,0.02,0.76,0.65,155,0,6209794,0,0

In [109]:
combined_history_with_names = combined_history_df.merge(
    players_df[["id", "web_name"]],
    left_on="element",
    right_on="id",
    how="left"
)

In [110]:
combined_history_with_names[
    ["web_name"] + important_fields
]

,web_name,element,round,total_points,minutes,goals_scored,assists,clean_sheets,goals_conceded,yellow_cards,red_cards,bonus,bps,expected_goals,expected_assists,expected_goal_involvements,expected_goals_conceded,influence,creativity,threat,ict_index
0,Saka,12,1,9,67,1,0,1,0,0,0,1,36,0.64,0.08,0.72,0.06,42.8,26.1,33.0,10.2
1,Haaland,411,1,2,90,0,0,0,1,0,0,0,6,0.74,0.02,0.76,0.65,3.8,5.2,50.0,5.9

In [112]:
value_display = combined_history_with_names[
    [
        "web_name",
        "round",
        "value",
        "total_points",
        "selected"
    ]
].copy()

value_display["price"] = value_display["value"] / 10

value_display[
    [
        "web_name",
        "round",
        "price",
        "total_points",
        "selected"
    ]
]

  web_name  round  price  total_points  selected
0     Saka      1    9.5             9    819914
1  Haaland      1   15.5             2   6209794

## Data Grain

### fct_player_gameweek

Grain: **One row per player per gameweek.**

This table stores a player's gameweek-level performance data, including:

- Total points
- Minutes played
- Goals scored
- Assists
- Clean sheets
- Bonus points
- BPS
- Expected goals (xG)
- Expected assists (xA)
- Expected goal involvements (xGI)
- ICT statistics
- Historical player price